### ISSUE TITLE
Add global variables

### ISSUE THREAD

**Issue by d-schn** [b-irsigler/komtur#141]
Currently, getting all necessary global variables into the scripts (such as the camera or nodes like christine that are always in the game) is lots of scripting. Using https://docs.godotengine.org/en/3.5/tutorials/scripting/singletons_autoload.html we can always load these at the start.

**Comment by b-irsigler** [comment]
This would also be useful for character properties when introducing item with boni.

**Comment by d-schn** [comment]
Started in branch for #139
