### ISSUE TITLE
User Request: Spinne shouldn't come too close to castle

### ISSUE THREAD

**Issue by b-irsigler** [b-irsigler/komtur#142]
How about we implement an attack of the Komtur against Spinne? Either it is killed after that or it is just scared away.

**Comment by d-schn** [comment]
attack against spinne also mentioned in #69 
If we do an npc overhaul we also need to fix Spinne scaling, it's basically not chasing the player until you run after it after the first deal
also Spinne should not be able to come close to chapel

**Comment by d-schn** [comment]
done
