### ISSUE TITLE
Der Gruene interaction

### ISSUE THREAD

**Issue by b-irsigler** [b-irsigler/komtur#75]
Let him ask a question like "Only one unbaptisted child for ten beeches!" Not weird at all...
Every time, we make the deal, Die Spinne should become bigger in size and maybe also faster.

**Comment by d-schn** [comment]
see [wiki](https://github.com/b-irsigler/komtur/wiki) for definition

**Comment by b-irsigler** [comment]
For the future, let's connect signals via code: https://docs.godotengine.org/en/3.3/getting_started/step_by_step/signals.html
