### ISSUE TITLE
Refactor signals into code

### ISSUE THREAD

**Issue by b-irsigler** [b-irsigler/komtur#84]
Connecting signals via UI makes it very hard to comprehend the code. Let's substitute all signals connection with code:
https://docs.godotengine.org/en/3.3/getting_started/step_by_step/signals.html
...same for timers

**Comment by d-schn** [comment]
Already done in code, wrote that into documentation as a convention: 
https://github.com/b-irsigler/komtur/wiki/dev-ressources
