### ISSUE TITLE
Add slow aura to Komtur

### ISSUE THREAD

**Issue by g-oelk** [b-irsigler/komtur#90]

**Comment by d-schn** [comment]
If we do the aura, the "attack" rant makes no sense
How about slowing down Christine for a set timer on hit? This timer could also be used to disable Komtur chase/attack so there is no stacking
Text: "Christine's Angst vor dem Komtur macht sie langsamer"

**Comment by d-schn** [comment]
implement debuff timer instead of using cooldown timer of komtur.
